FROM node:20.15-alpine AS base

ARG TARGET
 # runtime too
ENV TARGET=${TARGET}

RUN npm install -g pnpm@8.15.9

FROM base AS pruner
RUN npm install -g turbo@2.5.4
WORKDIR  /app
COPY . .
RUN turbo prune --scope=${TARGET} --docker

FROM base AS builder
WORKDIR /app
COPY --from=pruner /app/out/json/ .
RUN pnpm install

COPY --from=pruner  /app/out/full/ .
COPY turbo.json turbo.json

ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_s3_bucket
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

RUN pnpm turbo run build --filter=${TARGET}...

FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/apps/${TARGET}/public ./apps/${TARGET}/public
COPY --from=builder  --chown=nextjs:nodejs /app/apps/${TARGET}/.next/standalone/ ./
COPY --from=builder --chown=nextjs:nodejs  /app/apps/${TARGET}/.next/static ./apps/${TARGET}/.next/static
COPY --from=builder --chown=nextjs:nodejs  /app/apps/${TARGET}/.next/server ./apps/${TARGET}/.next/server

USER nextjs

EXPOSE 3000

ENV PORT=3000

CMD node apps/${TARGET}/server.js