# fly.toml app configuration file generated for sendshort-api on 2025-08-06T02:12:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sendshort-api'
primary_region = 'fra'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
  PORT = '8080'

[processes]
  web = 'node apps/api/dist/index.js'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  processes = ['web']

  [http_service.concurrency]
    type = 'requests'
    soft_limit = 500

[[vm]]
  size = 'performance-2x'
