services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./mock:/app/mock
      - ./src/:/app/src
      - ./public/:/app/public
      - ./remotion.config.ts/:/app/remotion.config.ts
    ports:
      - "3001:3001"
    env_file:
      - .env.local
    depends_on:
      - redis
