const FPS = 30;
const VIDEO_HEIGHT = 1920;
const VIDEO_WIDTH = 1080;
const UGC_HOOK_DURATION_IN_FRAMES = 4 * FPS; // 4 SECONDS

export { FPS, VIDEO_HEIGHT, VIDEO_WIDTH, UGC_HOOK_DURATION_IN_FRAMES };
